### PR TITLE
UI fixes/tweaks

### PR DESCRIPTION
**Pull request by ernestask**
Can’t come up with a better title. See commits.

### CODE REVIEW

**Comment by ernestask** [comment]
@rluzynski, if you get a chance, I would appreciate you giving this a spin. It seems to work for me, however.

**Comment by rluzynski** [comment]
I'm unable to test now and I can't even promise I can do it today.

Have you tested both in the environment which displays a menu button and in the one which does not? Both in GNOME-like and non-GNOME-like? LTR and RTL locales?

I think that the root cause of the problem is that I assumed that the left offset of the box in the header bar equals its padding. Since the menu button has been added the box is no longer the leftmost widget and the assumption above is no longer true. We still need ```2 * padding``` but we also need to add the actual left offset of the box and calculate ```padding``` correctly. I don't know how to calculate the padding correctly, I believe it belongs to the GTK styling engine.

**Comment by ernestask** [comment]
Right, I forgot to consider themes other than Adwaita.

**Comment by ernestask** [comment]
This should be fine now.

**Comment by rluzynski** [comment]
I'm sorry, I still didn't have time to test this patch. I still hope I will do it soon. However, I still have some doubts.

I don't understand what the "Center-align stack switcher" patch does, or rather why it does so.

Your implementation of measuring the header box looks great. However, I am not sure if we need to take the margins into account when calculating the relative position of the widgets. I don't remember exactly how I implemented the previous code but I think that margins were already included in the position of the widget while paddings were not.

Please test this as I suggested:

* in GNOME and non-GNOME,
* with and without the menu button,
* in LTR and RTL locales (LC_ALL=he_IL.utf8 or fa_IR.utf8 or ar_SA.utf8 etc.)
* also please tweak the margins and paddings and see if they are reflected correctly if they have some crazy large values.

If everything works fine then the patch is correct.

**Comment by ernestask** [comment]
> in GNOME and non-GNOME,

That really should not matter. GTK is GTK, the only difference is in themes.

> with and without the menu button,

That’s the main issue, how else would I test it?

> in LTR and RTL locales (LC_ALL=he_IL.utf8 or fa_IR.utf8 or ar_SA.utf8 etc.)

No need to change locales, the inspector allows switching directions (yes, I have tried that).

> also please tweak the margins and paddings and see if they are reflected correctly if they have some crazy large values.

That is why included margins in the calculation, because otherwise it would look broken.

**Comment by ernestask** [comment]
> I don't understand what the "Center-align stack switcher" patch does, or rather why it does so.

It makes the stack switcher centered horizontally. Try playing with pane sizes - you will notice that it remains anchored to the start of the box (or header bar, if you will). With the patch it will stay centered. Just something that I found more visually appealing.

**Comment by ernestask** [comment]
I can even come up with a few screencasts with different versions if you want.

**Comment by rluzynski** [comment]
OK, I've managed to test the patches. I don't see why the centered stack switcher looks better. If you really want to tweak then what about making it expand and fill entire space? @allanday, any opinion about it?

gnome-abrt-centered-box
The difference is that currently My/System switcher is always aligned to left while in the patched version it is centered between the left edge of the window and two buttons: [🔍][✓]

**Comment by rluzynski** [comment]
Regarding the second patch, unfortunately, something went wrong with my Fedora Rawhide and after today's update I am unable to hide the global app menu and show the fallback menu button. Therefore, I am unable to test the patch thoroughly. Few remarks, though:

* Your code retrieving paddings and margins from the styles looks great!
* I am not sure if we should take ```padding.right``` and ```margin.right``` into account. Consequently, if we skip them, in the RTL text direction we would have to skip ```padding.left``` and ```margin.left```, respectively.
* I'm afraid that we should also take ```self.box_panel_left.get_margin_start()``` and (maybe) ```self.box_panel_left.get_margin_end()``` into account. These values are independent on the CSS margins and both sum up.
* Also, I'm afraid that ```update_box_header_left_size_from_paned()``` requires similar tweaks. This is the code responsible for resizing the header when a user resizes the left panel. The code you tweaked so far is only responsible for setting the minimum width of the left panel depending on the minimum size of the header bar box.

> > in LTR and RTL locales (LC_ALL=he_IL.utf8 or fa_IR.utf8 or ar_SA.utf8 etc.)
>
> No need to change locales, the inspector allows switching directions (yes, I have tried that).

Perfect.

**Comment by rluzynski** [comment]
Just to be clear and not to make this pull request stalled: I am OK with the commit ```views: Fix side pane sizing``` - not because I am sure this is correct but because I am unable to test it more thoroughly. Also, even if it is not perfect it is still better than the current state: it improves things and does not break anything.

I am not OK with the commit ```oops-window.ui: Center-align stack switcher``` but that's just my personal opinion. If the actual maintainers decide they want this commit then it will be pushed anyway.

**Comment by ernestask** [comment]
It’s stalled, because I need to find some time to perfect the sizing code. Hoping for sometime this week.

**Comment by ernestask** [comment]
Dropped the alignment tweak.

**Comment by rluzynski** [comment]
Since the alignment tweak has been dropped I have no more remarks to this pull request. Somebody please review and test it, and consider merging.

**Comment by ernestask** [comment]
I completely forgot about this, but I’ll try to make time to make sure all cases are covered.

**Comment by ernestask** [comment]
For anyone interested: https://cloud.gnome.org/index.php/s/eM5Cd666oRepZBz

Going to merge this now.

**Pull request merged**
