### PR TITLE
A series of cherry-picks from wip/hadess/no-system-tab

### LINKED ISSUE #59: Don't show system crashers separately
Instead, they should be in the same sidebar, without the need for a toggle button.

https://github.com/gnome-design-team/gnome-mockups/raw/master/oops/oops-report.png
vs.
https://camo.githubusercontent.com/457381e233afb23fb85537f4daa8c1fac76051ba/68747470733a2f2f6a66696c616b2e6665646f726170656f706c652e6f72672f6d656469612f73686f7274656e65645f7265706f7274696e672f676e6f6d652d616272742d66756c6c2d7265706f72742d646f6e652e706e67

If getting access to the system crashers requires authentication of some sort, we should show a padlock in the top bar (see gnome-control-center's Printers panel for example).

### PR DESCRIPTION
**Pull request by rluzynski**
This is a series of cherry-picks from @hadess' branch `wip/hadess/no-system-tab`. Only 6 out of 12 have been cherry-picked and here are the reasons why the others have not been:

1. `BROKEN: Remove My/System problems list switcher` - 7ef4577 - first, the caption says it is broken; second, AFAIK we are not yet ready to close #59.
2. `Remove "ABRT Configuration" dialogue` - 1204b37 - looks destructive to me because just removes it completely without providing any alternative.
3. `Relayout right-hand pane` - 44a2d1d - I think it has been obsoleted by fixing #98.
4. `Fix margins in right-hand pane` - dd1e9d9 - idem.
5. `Remove unused "header_bar" member` - 76239db - it's still used, @hadess made it unused in 7ef4577 which is not (yet) ready.
6. `Remove inotify problem source` - 9904fd6 - looks destructive to me and I will not cherry-pick it before I understand what it is doing and why it is needed.

Feel free to cherry-pick only some of my cherry-picks and add more @hadess' commits which I have not cherry-picked although I tried my best to decide which of these commits are OK to push to master.

### CODE REVIEW

**Comment by rluzynski** [comment]
Just to make it clear: I've asked @hadess on IRC if it's OK to review and cherry-pick some of his commits to master and he agreed.

**Comment by jfilak** [comment]
Thank you for the pull request. It looks like " 	Fix dim-label being applied to proper app icons" commit fixes  "Add dim-label to icon" commit. I try to avoid commit fixing another commits in a single pull request. Can you please squash these two commits into a single one, if it is possible. Otherwise the pull request looks good.

**Comment by rluzynski** [comment]
That's true, indeed. I was trying to reproduce @hadess' workflow, bug to bug and bugfix to bugfix. No problem, I will prepare a pull request without this buggy commit.

**Comment by rluzynski** [comment]
OK, done. Please note that the history of my fork has been rewritten, you must force refresh if you have its copy locally.

**Comment by rluzynski** [comment]
@allanday agrees to remove the backend configuration dialog so the commit 1204b37 has been cherry-picked, too. Please see the new history.

**Comment by jfilak** [comment]
I've fixed few pylint warnings and pushed these commits:
eb3ea2f Disambiguate the word "System"
15f1c9a Implement pgettext and its alias C_
60183a7 Reword "Detected" to "First Detected"
4146437 Use "Problem Reporting" as the program name in the About box
6fa8855 Revert "Add 'Report problem with ABRT' dialog"
773712e Fix dim-label being applied to proper app icons
e14ce17 Make "Select" button unsensitive when list is empty
fa8a281 Make titlebar blue in selection mode
b755e2f Use dim-label style, not hard-coded colours for labels
3ce72c9 Remove "ABRT Configuration" dialogue
3f3fca3 Add search button

**Pull request closed without merging**
