### PR TITLE
problems: Use GTask to fetch report page titles

### PR DESCRIPTION
**Pull request by ernestask**
The current solution was broken, disabled, got more broken over time and
just in general is cumbersome. With GTask, we can avoid reinventing some
wheels.

This does require glib 2.63.0+ and gobject-introspection 1.63.0+(?),
since the used API is currently not introspectable.

Closes https://github.com/abrt/gnome-abrt/issues/25
Resolves https://github.com/abrt/gnome-abrt/issues/96

Signed-off-by: Ernestas Kulik <ekulik@redhat.com>

### CODE REVIEW

**Comment by ernestask** [comment]
Now we need to decide whether this is useful. I could just remove the code without replacing it. I can see someone being surprised by the sudden change in text, but a good old spinneroo might do the trick, too.

**Comment by ernestask** [comment]
Also depends on https://github.com/abrt/faf/pull/840.

**Comment by ernestask** [comment]
> What is default and why is it failing?

It’s an internal job that inserts backdoors into the project.

**Comment by StykMartin** [comment]
> > What is default and why is it failing?
> 
> It’s an internal job that inserts backdoors into the project.

I mean why everything is failing

**Comment by ernestask** [comment]
> > > What is default and why is it failing?
> > 
> > 
> > It’s an internal job that inserts backdoors into the project.
> 
> I mean why everything is failing

We call it failure-driven development.

**Comment by StykMartin** [comment]
Any status update @ernestask

**Comment by ernestask** [comment]
Ano, prosím. I can merge this once GLib is released with the changes I need for this and once the version is built for stable Fedora releases.

**Comment by ernestask** [comment]
GNOME 3.36 will be out on March 11th, so, after some delay to allow for building Fedora packages, we can merge this.

**Comment by mgrabovsky** [comment]
This doesn't seem right 🤔

Screenshot from 2020-05-04 17-14-22

**Comment by ernestask** [comment]
https://github.com/abrt/gnome-abrt/pull/241#issuecomment-553779264 should have fixed that, as I recall.

**Comment by ernestask** [comment]
Possibly the change has not been deployed in any instance we control, because of the rename and stuff.

**Comment by ernestask** [comment]
Could be backported to the 1.x branch, though.

**Comment by mgrabovsky** [comment]
> [#241 (comment)](https://github.com/abrt/gnome-abrt/pull/241#issuecomment-553779264) should have fixed that, as I recall.

Oh, right, missed that.

**Comment by ernestask** [comment]
https://github.com/abrt/faf/commit/a57d06b7d572d6e5197384b5eca7b97b10ad46ec

I can do a 1.3.10 when I’m back next week.

**Comment by ernestask** [comment]
Now it should work.

**Pull request merged**
