### PR TITLE
icon: update app icon

### PR DESCRIPTION
**Pull request by jimmac**
- update app icon based on the new guidelines.
  See https://gitlab.gnome.org/GNOME/Initiatives/issues/2 for
  more info.
- unsure what the status icon is used for, thus keeping it.
- there is no source artwork, the final art is the source.

Addresses https://github.com/abrt/gnome-abrt/issues/224

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by ernestask** [comment]
> unsure what the status icon is used for, thus keeping it.

I can’t tell, either. It’s not like we use `GtkStatusIcon` anywhere.

**Comment by ernestask** [comment]
I say we remove the status icons and the private icon nonsense. Can you do that?

**Comment by mkutlak** [comment]
@trapas add to whitelist

These should be wiped with the rest: 
https://github.com/abrt/gnome-abrt/blob/de6e5072e82b36b24548fbc41f8ce2855a47ef1f/icons/Makefile.am#L60
https://github.com/abrt/gnome-abrt/blob/de6e5072e82b36b24548fbc41f8ce2855a47ef1f/icons/Makefile.am#L77

**Comment by mkutlak** [comment]
Build log error:
```
DEBUG: RPM build errors:
DEBUG: BUILDSTDERR:     File not found: /builddir/build/BUILDROOT/gnome-abrt-1.2.7.16.g7ccb-1.fc30.x86_64/usr/share/icons/hicolor/*/status/*
DEBUG: Child return code was: 1
```

This line should be deleted too:
https://github.com/abrt/gnome-abrt/blob/de6e5072e82b36b24548fbc41f8ce2855a47ef1f/gnome-abrt.spec.in#L88

**Pull request merged**
