### PR TITLE
Details pane: new design

### LINKED ISSUE #98: Grid align content in details pane
abrt-grid-align
Reducing the number of alignment points will make the pane look tidier and easier to read. A key feature of this is to align the list columns to the icon and heading above, and to move the status message text to the left.

Mockup attached.

### LINKED ISSUE #129: "The problem data are incomplete..." text lacks padding
See attached screenshot; the text lacks some padding on the right hand side.
screenshot from 2015-05-19 21-09-29

### PR DESCRIPTION
**Pull request by rluzynski**
The details grid reworked according to Allan's new design.
This also fixes some other minor UI design issues like missing
right margin reported by Cosimo.

Closes #98
Closes #129

### CODE REVIEW

**Comment by allanday** [comment]
Looks good to me - much better. The one issue I see is the line of text along the bottom. This is a long way from the list above, which can result in awkward layouts (particularly when the window is very big).

You could use the same vertical padding above and below the list.

**Comment by rluzynski** [comment]
Thanks for your comment, Allan. It's not clear to me which widget you mean as *the line of text along the bottom.* Is it the part which says *Status string. This should be long...* in [your design](https://github.com/abrt/gnome-abrt/issues/98)? It is placed in the middle between the list of properties/values (the one which says *Name: Foo, Version: 0.1.2* etc.) and the bottom of the page. The vertical padding above and below it should be the same. In fact, this patch does not change it, the old (current) version is the same. Do you want it to be different, for example do you want it to be top aligned, that means placed directly under the list of properties/values plus some fixed padding?

You can run the GtkInspector (Ctrl+Shift+I), select the widget and manipulate its properties live.

**Comment by rluzynski** [comment]
OK, after an IRC conversation it's clear to me that the `vbx_problem_messages` box should be moved up and be placed under `vbx_links` with some padding but without a large gap. Here is the new commit which implements this. Allan, if you would like to test this new patch and you don't like the padding you can change its value, it is `margin_top` of `vbx_problem_messages` and it is 12px at the moment.

**Note:** I have rewritten the history of my branch, the old commit is outdated now and you should not use it. If you have a local copy of my branch then probably the best you can do is delete it (or revert to master) and then copy again. Sorry for any inconvenience.

**Comment by jfilak** [comment]
LGTM

**Comment by allanday** [comment]
Looks good with the latest updates. Would be good to increase the padding above vbx_problem_messages, so the spacing is equal above and below vbx_links.

**Comment by rluzynski** [comment]
@allanday - please provide more details. The padding above `vbx_problem_messages` is actually the same as the padding above the list of properties and below the app icon, it is always 12px. You may notice a larger vertical space between the icon and the properties because the icon widget requires 156px height while the icon is actually usually 64x64px. Please apply this patch again (locally), please use GtkInspector or use Glade to open oops.glade and choose the value of `margin_top` of `vbx_problem_messages` which you find satisfying. I hope we can fix this problem very soon.

**Comment by rluzynski** [comment]
@allanday - please provide more details. The padding above `vbx_problem_messages` is actually the same as the padding above the list of properties and below the app icon, it is always 12px. You may notice a larger vertical space between the icon and the properties because the icon widget requires 156px height while the icon is actually usually 64x64px. Please apply this patch again (locally), please use GtkInspector or use Glade to open oops.glade and choose the value of `margin_top` of `vbx_problem_messages` which you find satisfying. I hope we can fix this problem very soon.

**Comment by rluzynski** [comment]
@allanday - please provide more details. The padding above `vbx_problem_messages` is actually the same as the padding above the list of properties and below the app icon, it is always 12px. You may notice a larger vertical space between the icon and the properties because the icon widget requires 156px height while the icon is actually usually 64x64px. Please apply this patch again (locally), please use GtkInspector or use Glade to open oops.glade and choose the value of `margin_top` of `vbx_problem_messages` which you find satisfying. I hope we can fix this problem very soon.

**Comment by rluzynski** [comment]
@allanday - please provide more details. The padding above `vbx_problem_messages` is actually the same as the padding above the list of properties and below the app icon, it is always 12px. You may notice a larger vertical space between the icon and the properties because the icon widget requires 156px height while the icon is actually usually 64x64px. Please apply this patch again (locally), please use GtkInspector or use Glade to open oops.glade and choose the value of `margin_top` of `vbx_problem_messages` which you find satisfying. I hope we can fix this problem very soon.

**Comment by rluzynski** [comment]
Sorry for multiple comments - buggy Android browser. :(

**Comment by jfilak** [comment]
Thank you very much! I cherry-picked your commit and have pushed https://github.com/abrt/gnome-abrt/commit/46b6280f18f19be844544004fb9ee9b339e1683f

**Pull request closed without merging**
