### PR TITLE
spec: Add python3-beautifulsoup4 dependency

### PR DESCRIPTION
**Pull request by ernestask**
Fallout from 837cb787caa4667a928673353e4ea8205ef9419a.

https://bugzilla.redhat.com/show_bug.cgi?id=1836634
https://bugzilla.redhat.com/show_bug.cgi?id=1836738

### CODE REVIEW

**Comment by mgrabovsky** [comment]
Should this be added to `meson.build` as well?

**Comment by ernestask** [comment]
I’m not sure where it’s needed during the build.

**Comment by xsuchy** [comment]
I guess that it is needed as well, but we have in %check || :

**Comment by ernestask** [comment]
Well, really, most of the Python build dependencies in the spec file are bogus, because we neither have the tests, nor are they used in building the CPython wrapper.

I could write some kind of regression test for this and then we would use *some* of them.

**Pull request merged**
